### ISSUE TITLE
Documentation edit suggestions

### ISSUE THREAD

**Issue by RichardLitt** [splitrb/split-analytics#29]
:wave: Hey there! This is the developer experience audit from @mntnr for this repository. I've added in my thoughts below, in the form of a checklist. Looking forward to seeing what you think; let's see if we can resolve all of the open issues and make this repository shine ✨ 💖 ✨

# Repository Review: [splitrb/split-analytics](https://github.com/splitrb/split-analytics)

> :bar_chart: An extension to Split to push test data to Google Analytics.

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose. If I think that something is fine, even if it isn't valid according to this checklist, I've checked it off and included a note._

### Reviewing the Repository Docs

- [x] Is there a README?
  - [ ] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)? _See TODO section below for non-conforming criteria._
  - [x] Is it spellchecked? _15 warnings, all false positives._
- [x] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [~] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [x] Does it reference an email address for violations?
  - [ ] Does it reference a second email address? _See TODO section for a note on this._
- [x] Is there a `LICENSE` file?
  - [x] Is this matched in the `.gemspec`?
  - [~] Is the year correct? _Year is 2015 (NB: latest release is 2016)._
- [ ] Is there a `.github` or `docs` folder? _See TODO section below for recommendation._
  - [ ] Is there an `ISSUE_TEMPLATE.md`?
  - [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?
- [~] Is there a `CONTRIBUTING.md` file? _See TODO section below for recommendation._
  - [~] Does it mention how to make a PR?
  - [ ] Does it mention what sort of issues you'd like?
  - [ ] Does it mention a `good first issue` label as a starting point?
  - [ ] Does it mention triaging and bug reports as good starting points?
  - [ ] Does it point to a community chat program, like Slack or Gitter?
  - [ ] Does it encourage conversations in issues before opening huge PRs?
  - [ ] Does it specify where to ask questions on process?
  - [ ] Does it explain labels used in the issues?
- [ ] Is there a `CHANGELOG`?
  - [ ] If there isn't, are notes included in the project's releases?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`. _5 warnings, all false positives._
- [x] Does the repository name itself pass on http://wordsafety.com?

### Process

- [x] Can I install easily?
- [x] Can I use this easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests? _0 open, 7 closed at time of audit._
- [x] Are there an acceptable amount of issues? _2 open, 19 closed at time of audit._
- [x] Are an acceptable amount of issues less than six months old? _0 open, 1 closed at time of audit._
- [x] Are there useful issue labels?
- [x] Are the labels being used?
- [ ] Is there a `good for beginners` or `good first issue` label?
- [ ] Is there a `waiting on contributor` label?

### Bots

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [ ] Are there bots enabled?
- [ ] ~~Are the bots listed in the Contribute or Readme files so that users can expect to interact with them?~~ _N/A._

### Metadata
- [x] Is there a description on GitHub?
  - [~] Does the description match the README?
- [ ] Are the topics useful? _No topics; this is noted in the TODO below._
- [x] Is there a website?
  - [x] Does the website match the project?
  * _Mostly. The documentation pulls directly from the GitHub README, but the installation is a little different (the website indicates to pass a version flag, which the GH readme does not)._

### Package Metadata

_Note: These should apply to `.gemspec` here._

- [x] Does the description match the GitHub description? _But see note in the TODO section below about the GH description; if that changes, then this should, too._
- [~] Is there a `bugs` field?
- [x] Is there a `homepage` field?
- [ ] Are there appropriate `keywords`?
  - [ ] ~~Do these match the topics on GitHub?~~ _N/A._

### TODO

- [~] Make changes so that the README conforms to the standard-readme spec; the following criteria aren't met:
- [ ] As this is an extension to split, consider pointing back to split for duplicative elements which you do not want to replicate in its extensions, such as info on how to contribute (including) how to manage issues and PRs. If not, I recommend creating a `CONTRIBUTE.md` similar to the main split repo's (see list above for recommended elements to include).
- [ ] I recommend either creating a CHANGELOG, or including a note in each release briefly stating what the release included (this was done for one release but no others).
- [ ] I would recommend adding topics to the repo below the GH description.

#### Generic
- [ ] I would add a maintainers section, to make it clear who is on the maintainers team. This helps set expectations and clarifies for the users who they can talk to.
- [ ] Add `https` to your repository website link. Currently it is `http`.
- [ ] Add a link to your Google Groups you reference in the main split repo. You want to engage with users there.
- [ ] Consider adding a secondary email to the Code of Conduct as a contact - someone may have an issue with _you_ but not want to tell you directly. I know, this idea may be awkward. But you will give them an option in case they do have an option, and this may be good for the overall health of the project. I'd be happy to add my name here, if you need a second one.
- [ ] Consider adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to your repository. It looks like you have your PRs well under control, but these may help you in the future. At the least, ask them to run the tests, first, and to read the Usage guides.
- [ ] This audit does _not_ cover license dependency. For that, I suggest using either [licensee](https://github.com/jslicense/licensee.js) or an external tool like [Fossa](https://fossa.io/). Let me know if you want more help here.

#### Issues
- [ ] Consider adding `available` labels as well as `good first issue`. These can be used to signal that you're looking for community involvement for issues. They can also be configured to display on http://up-for-grabs.net. This will help more people interact with your code, and lead to small, iterative work done by others. It may take some time to set up initially - properly scoping issues for newcomers takes some time - but the payback should be worth it.
- [ ] I label pull requests where I am waiting on the Contributor to respond `waiting on contributor`. This helps alleviate pressure on you to close them.

## Contribute back?

This checklist is open source! If you have suggestions or think it could be better, contribute back on [mntnr/audit-templates](https://github.com/mntnr/audit-templates).

As well - note that you don't need to tick every box. If you have anything you'd like to talk about, I'm here; otherwise, I would suggest either pulling out tasks into a comment before, or into other issues, and then closing the issue when you feel you've adequately done everything. If you want help here, let me know.

Thank you!
